Kafka in Kubernetes
gznznzjsn/car-microservices pull request #8
Opened 2023-04-04 11:18 UTC by gznznzjsn

2023-04-04 12:17 UTC, h1alexbel requested changes

2023-04-04 12:17 UTC, h1alexbel commented on kubernetes/task-service/redis/ts-redis-stateful.yaml
> +  replicas: 1
set more replicas, 3 is a good choice

2023-04-04 12:17 UTC, h1alexbel commented on kubernetes/task-service/task-service-deployment.yaml
> +  replicas: 1
set more replicas, 3 is a good choice

2023-04-04 12:17 UTC, h1alexbel commented on kubernetes/zookeeper/zookeeper-stateful.yaml
> +  replicas: 1
set more replicas, 3 is a good choice

2023-04-04 12:17 UTC, h1alexbel commented on kubernetes/task-service/mongo/ts-mongo-stateful.yaml
> +  replicas: 1
set more replicas, 3 is a good choice

2023-04-04 12:17 UTC, h1alexbel commented on kubernetes/order-service/postgres/os-postgres-stateful.yaml
> +  replicas: 1
set more replicas, 3 is a good choice

2023-04-04 12:17 UTC, h1alexbel commented on kubernetes/order-service/order-service-deployment.yaml
> +  replicas: 1
set more replicas, 3 is a good choice

2023-04-04 12:17 UTC, h1alexbel commented on kubernetes/kafka/kafka-deployment.yaml
> +  replicas: 1
set more replicas, 3 is a good choice

2023-04-05 07:57 UTC, gznznzjsn commented
@h1alexbel everything is done here

2023-04-05 09:28 UTC, h1alexbel commented on kubernetes/zookeeper/zookeeper-stateful.yaml
> +#      volumes:
@gznznzjsn why do you remove volumes?

2023-04-05 10:11 UTC, gznznzjsn commented on kubernetes/zookeeper/zookeeper-stateful.yaml
> +#      volumes:
I had a problem with it, so I commented it. Now problem is gone, forgot to bring volume back

2023-04-05 10:52 UTC, merged