All services and Istio ingress configured in Kubernetes
gznznzjsn/car-microservices pull request #9
Opened 2023-04-13 09:51 UTC by gznznzjsn

2023-04-13 11:32 UTC, h1alexbel requested changes
1st submission was misclicked

2023-04-13 14:25 UTC, gznznzjsn commented on kubernetes/axon/axonserver-service.yaml
> +---
My fault

2023-04-13 14:26 UTC, gznznzjsn commented on kubernetes/run.sh
> +minikube tunnel
Done

2023-04-13 14:27 UTC, gznznzjsn commented on kubernetes/employee-service/employee-service-secret.yaml
> +  SPRING_DATA_MONGODB_PASSWORD: cGFzc3dvcmQ=
Done

2023-04-14 10:52 UTC, h1alexbel requested changes

2023-04-14 10:52 UTC, h1alexbel commented on kubernetes/inventory-service/inventory-service-configmap.yaml
> +  SPRING_DATA_MONGODB_HOST: 'is-mongo-service'
fix the prefixes, SPRING -> APP, or something equal

2023-04-17 11:39 UTC, h1alexbel approved these changes

2023-04-17 11:40 UTC, merged